[ansible]
short = "ansible"
full = "pipx:ansible"
explicit_backend = false

[duckdb]
short = "duckdb"
full = "aqua:duckdb/duckdb"
explicit_backend = false

[fastfetch]
short = "fastfetch"
full = "aqua:fastfetch-cli/fastfetch"
explicit_backend = false

[fd]
short = "fd"
full = "aqua:sharkdp/fd"
explicit_backend = false

[just]
short = "just"
full = "aqua:casey/just"
explicit_backend = false

[lazydocker]
short = "lazydocker"
full = "aqua:jesseduffield/lazydocker"
explicit_backend = false

[lazygit]
short = "lazygit"
full = "aqua:jesseduffield/lazygit"
explicit_backend = false

[oci]
short = "oci"
full = "asdf:oci"
explicit_backend = true

[opencode]
short = "opencode"
full = "aqua:anomalyco/opencode"
explicit_backend = false

[watchexec]
short = "watchexec"
full = "aqua:watchexec/watchexec"
explicit_backend = false