[fd]
short = "fd"
full = "aqua:sharkdp/fd"
explicit_backend = false

[lazydocker]
short = "lazydocker"
full = "aqua:jesseduffield/lazydocker"
explicit_backend = false

[lazygit]
short = "lazygit"
full = "aqua:jesseduffield/lazygit"
explicit_backend = false