general {
  layout = dwindle
}

dwindle {
        # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
        pseudotile = true
        preserve_split = true
        force_split=0
        smart_resizing = true
        smart_split = false
        precise_mouse_move = true
}
master {
    allow_small_split = true
    mfact = 0.50
    orientation = center
    drop_at_cursor = yes
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    # new_is_master = false
    # new_on_top = true
    # always_center_master = true
}
