-- hl.config({
--   plugin = {
--     hyprbars = {
--       enabled = false,
--       bar_height = 30,
--       bar_blur = true,
--       bar_part_of_window = false,
--       on_double_click = "hyprctl dispatch fullscreen 1",
--     },
--   },
-- })

-- hl.plugin.hyprbars.add_button({
--   bg_color = "rgb(ff4040)",
--   fg_color = "rgb(ffffff)",
--   size = 10,
--   icon = "X",
--   action = "hyprctl dispatch 'hl.dsp.window.close()'",
-- })
--
-- hl.plugin.hyprbars.add_button({
--   bg_color = "rgb(eeee11)",
--   fg_color = "rgb(000000)",
--   size = 10,
--   icon = "_",
--   action = [[hyprctl dispatch 'hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" })']],
-- })
