[mgr]
show_hidden = true
show_symlink = true
[flavor]
dark = "catppuccin-mocha"
# # [[plugin.prepend_previewers]]
# # name = "*/"
# # run = "eza-preview"
# #
[plugin]
prepend_previewers = [
  { url = "*.csv", run = "duckdb" },
  { url = "*.tsv", run = "duckdb" },
  { url = "*.json", run = "duckdb" },
  { url = "*.parquet", run = "duckdb" },
  { url = "*.txt", run = "duckdb" },
  { url = "*.xlsx", run = "duckdb" },
  { url = "*.db", run = "duckdb" },
  { url = "*.duckdb", run = "duckdb" },
  { url = "*.{3mf,obj,pts,ply,stl,step,stp}", run='piper -- f3d --no-background -taq --resolution 100,100 --output /tmp/f3d/preview.png -- $1 && timg -g100x100 -C --fit-width /tmp/f3d/preview.png' },
]

prepend_preloaders = [
  { url = "*.csv", run = "duckdb", multi = false },
  { url = "*.tsv", run = "duckdb", multi = false },
  { url = "*.json", run = "duckdb", multi = false },
  { url = "*.parquet", run = "duckdb", multi = false },
  { url = "*.txt", run = "duckdb", multi = false },
  { url = "*.xlsx", run = "duckdb", multi = false },
  # { url = "*.{3mf,obj,pts,ply,stl,step,stp}", run="f3d-preview"},
]

prepend_spotters = [
  # use the plugin for a specific mime type
  { mime = "audio/*", run = "spot" },
  # use as a spotter for all directories
  { url = "*/", run = "spot" },
  # use as a fallback for all files that don't have a spotter
  { url = "*", run = "spot" },
]
