add_newline = false
continuation_prompt = "› "

format = """
$sudo$directory$time$container$all
"""

#format = """$character"""
# right_format = """$gcloud$nodejs($package)"""
[character]
success_symbol = "[»]( #cdd6f4)"
error_symbol = "[»](#f38ba8)"

[cmd_duration]
show_milliseconds = true
min_time = 10

[container]
style = "red"
symbol = ""
format = "[$symbol $name]($style) "

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "
style = "#7aa2f7 bold"

[directory]
truncation_length = 3
truncate_to_repo = false
read_only = " 󰌾"
style = "#f9e2af bold"
read_only_style = "#fab387"
home_symbol = "~"
truncation_symbol = "../"
use_logical_path = false


[docker_context]
symbol = " "

[dotnet]
detect_files = [
  "global.json",
  "Directory.Build.props",
  "Directory.Build.targets",
  "Packages.props",
]

[elixir]
symbol = " "

[elm]
symbol = " "

[gcloud]
format = '[$symbol$active]($style) '
symbol = "󱇶 "
# disabled = false

[git_branch]
symbol = " "
# format = "[$symbol$branch]($style)[:$remote_name/$remote_branch](#f7768e)"
style = "#ff9e64 bold"
always_show_remote = false

[git_commit]
tag_symbol = "  "
format = "[\\[$hash$tag\\]]($style) "
disabled = true
# only_detached = true
# tag_disabled = true
style = "#e0af68 bold dimmed"

[git_metrics]
disabled = true

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "#e0af68 dimmed"
stashed = "S"
disabled = true
[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
detect_extensions = []

[package]
symbol = " "
# symbol = ""
format = "is [$symbol$version]($style) "
style = "#7dcfff dimmed bold"
display_private = true

[perl]
symbol = " "

[php]
symbol = " "
disabled = false

[python]
symbol = " "
disabled = false


[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[sudo]
disabled = false
symbol = " "
style = "#f7768e"
# command_timeout = 100
format = "[$symbol]($style)"

[swift]
symbol = "ﯣ "

[time]
disabled = false
format = "[$time]($style) "
style = "green bold"

[username]
show_always = false
format = "[$user]($style)"
style_user = "white bold"
style_root = "red bold"

[hostname]
ssh_only = true
format = "@[$hostname]($style) "
style = "purple bold"
